# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://145.223.20.134:5432/Study_Portal_Dev
spring.datasource.username=Study@portal
spring.datasource.password=Study@portal
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Configuration
server.address=0.0.0.0
server.port=8081

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=sumaiyyajamadar2190@gmail.com
spring.mail.password=samjam@123
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.startssl.enable=true

# HikariCP Configuration
spring.datasource.hikari.connection-timeout=30000  
spring.datasource.hikari.maximum-pool-size=5   
spring.datasource.hikari.minimum-idle=10       
spring.datasource.hikari.idle-timeout=3000      
spring.datasource.hikari.max-lifetime=900000           
spring.datasource.hikari.leak-detection-threshold=10000 

# Swagger Configuration
swagger.title=Study Portal REST API [DEVELOPMENT]

# JWT Keys
jwt.privateKey.path=/home/streesaktiuser/private-key.pem
jwt.publicKey.path=/home/streesaktiuser/public-key.pem