# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/study_portal_java
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.web=DEBUG
server.port=8082

spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.username =sumaiyyajamadar2190@gmail.com
spring.mail.password = samjam@123
spring.mail.properties.mail.smtp.starttls.required = true

# Other properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.startssl.enable=true

# HikariCP Configuration
 # 30 seconds timeout for getting a connection
spring.datasource.hikari.connection-timeout=30000  
# Maximum number of connections in the pool     
spring.datasource.hikari.maximum-pool-size=5   
# Minimum number of idle connections in the pool         
spring.datasource.hikari.minimum-idle=10       
 # 5 minutes timeout for idle connections           
spring.datasource.hikari.idle-timeout=3000      
  # 15 minutes maximum lifetime of a connection      
spring.datasource.hikari.max-lifetime=900000           
spring.datasource.hikari.leak-detection-threshold=10000 


#Swagger
swagger.title=Study Portal Management REST API [LOCAL]

#Config
https.server.url=https://StudyPortal.org
http.server.url=http://StudyPortal.org

# JWT Keys
jwt.privateKey.path=D:/home/streesaktiuser/private-key.pem
jwt.publicKey.path=D:/home/streesaktiuser/public-key.pem

spring.redis.host=127.0.0.1
spring.redis.port=6379


# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
